#pragma warning disable AA0005, AA0008, AA0018, AA0021, AA0072, AA0137, AA0201, AA0204, AA0206, AA0218, AA0228, AL0254, AL0424, AS0011, AW0006 // ForNAV settings

Report 50387 "BOSA Receipt Slip"
{
    RDLCLayout = './Layouts/BOSA Receipt Slip.rdlc';
    DefaultLayout = RDLC;

    dataset
    {
        dataitem("Receipts & Payments"; "Receipts & Payments")
        {
            RequestFilterFields = "Transaction No.", "Account No.", Amount, "Cheque No.", "Employer No.";
            column(ReportForNavId_1102755000; 1102755000) { } // Autogenerated by ForNav - Do not delete
            column(TransactionNo_ReceiptsPayments; "Receipts & Payments"."Transaction No.")
            {
            }
            column(NumberText_1_; NumberText[1])
            {
            }
            column(AccountNo_ReceiptsPayments; "Receipts & Payments"."Account No.")
            {
            }
            column(Name_ReceiptsPayments; "Receipts & Payments".Name)
            {
            }
            column(Amount_ReceiptsPayments; "Receipts & Payments".Amount)
            {
            }
            column(ChequeNo_ReceiptsPayments; "Receipts & Payments"."Cheque No.")
            {
            }
            column(ChequeDate_ReceiptsPayments; "Receipts & Payments"."Cheque Date")
            {
            }
            column(Posted_ReceiptsPayments; "Receipts & Payments".Posted)
            {
            }
            column(BankNo_ReceiptsPayments; "Receipts & Payments"."Employer No.")
            {
            }
            column(UserID_ReceiptsPayments; "Receipts & Payments"."User ID")
            {
            }
            column(AllocatedAmount_ReceiptsPayments; "Receipts & Payments"."Allocated Amount")
            {
            }
            column(TransactionDate_ReceiptsPayments; Format("Receipts & Payments"."Transaction Date"))
            {
            }
            column(TransactionTime_ReceiptsPayments; "Receipts & Payments"."Transaction Time")
            {
            }
            column(NoSeries_ReceiptsPayments; "Receipts & Payments"."No. Series")
            {
            }
            column(AccountType_ReceiptsPayments; "Receipts & Payments"."Account Type")
            {
            }
            column(TransactionSlipType_ReceiptsPayments; "Receipts & Payments"."Transaction Slip Type")
            {
            }
            column(BankName_ReceiptsPayments; "Receipts & Payments"."Bank Name")
            {
            }
            column(Insuarance_ReceiptsPayments; "Receipts & Payments".Insuarance)
            {
            }
            column(id_no; Cust."ID No.")
            {
            }
            column(emp_no; Cust."Personal No")
            {
            }
            column(UnallocatedAmount_ReceiptsPayments; "Receipts & Payments"."Un allocated Amount")
            {
            }
            column(User; "Receipts & Payments"."User ID")
            {
            }
            column(Remarks_ReceiptsPayments; "Receipts & Payments".Remarks)
            {
            }
            column(CompanyName; companyInfo.Name)
            {
            }
            column(CompanyAddress; companyInfo.Address)
            {
            }
            column(CompanyCity; companyInfo.City)
            {
            }
            column(CompanyPhoneNo; companyInfo."Phone No.")
            {
            }
            column(CompanyPicture; companyInfo.Picture)
            {
            }
            dataitem("Receipt Allocation"; "Receipt Allocation")
            {
                DataItemLink = "Document No" = field("Transaction No.");
                column(ReportForNavId_1102755001; 1102755001) { } // Autogenerated by ForNav - Do not delete
                column(DocumentNo_ReceiptAllocation; "Receipt Allocation"."Document No")
                {
                }
                column(MemberNo_ReceiptAllocation; "Receipt Allocation"."Member No")
                {
                }
                column(TransactionType_ReceiptAllocation; "Receipt Allocation"."Transaction Type")
                {
                }
                column(LoanNo_ReceiptAllocation; "Receipt Allocation"."Loan No.")
                {
                }
                column(Amount_ReceiptAllocation; "Receipt Allocation".Amount)
                {
                }
                column(InterestAmount_ReceiptAllocation; "Receipt Allocation"."Interest Amount")
                {
                }
                column(TotalAmount_ReceiptAllocation; "Receipt Allocation"."Total Amount")
                {
                }
                column(AmountBalance_ReceiptAllocation; "Receipt Allocation"."Amount Balance")
                {
                }
                column(InterestBalance_ReceiptAllocation; "Receipt Allocation"."Interest Balance")
                {
                }
                column(LoanID_ReceiptAllocation; "Receipt Allocation"."Loan ID")
                {
                }
                column(PrepaymentDate_ReceiptAllocation; "Receipt Allocation"."Prepayment Date")
                {
                }
                column(LoanInsurance_ReceiptAllocation; "Receipt Allocation"."Loan Insurance")
                {
                }
                column(AppliedAmount_ReceiptAllocation; "Receipt Allocation"."Applied Amount")
                {
                }
                column(Insurance_ReceiptAllocation; "Receipt Allocation".Insurance)
                {
                }
                column(UnAllocatedAmount_ReceiptAllocation; "Receipt Allocation"."Un Allocated Amount")
                {
                }
                column(GlobalDimension1Code_ReceiptAllocation; "Receipt Allocation"."Global Dimension 1 Code")
                {
                }
                column(GlobalDimension2Code_ReceiptAllocation; "Receipt Allocation"."Global Dimension 2 Code")
                {
                }
                column(LoanProduct; LoanProduct)
                {
                }
                column(Description_ReceiptAllocation; "Receipt Allocation".Description)
                {
                }
                trigger OnAfterGetRecord();
                begin
                    LoanProduct := '';
                    if "Receipt Allocation"."Loan No." <> '' then begin
                        if LoansRec.Get("Receipt Allocation"."Loan No.") then begin
                            LoanProduct := LoansRec."Loan Product Type Name";
                        end;
                    end;
                end;

            }
            trigger OnPreDataItem();
            begin
                companyInfo.Get();
                companyInfo.CalcFields(companyInfo.Picture);
            end;

            trigger OnAfterGetRecord();
            begin
                if Cust.Get("Receipts & Payments"."Account No.") then
                    Comms := 0;

                // Convert amount to words (British English style)
                NumberText[1] := ConvertAmountToWords(ROUND(Amount, 1));
            end;

        }
    }
    requestpage
    {
        SaveValues = false;
        layout
        {
            area(Content)
            {
                group(Options)
                {
                    Caption = 'Options';
                    field(ForNavOpenDesigner; ReportForNavOpenDesigner)
                    {
                        ApplicationArea = Basic;
                        Caption = 'Design';
                        Visible = ReportForNavAllowDesign;
                    }
                }
            }
        }

    }

    trigger OnInitReport()
    begin


    end;

    trigger OnPostReport()
    begin
    end;

    trigger OnPreReport()
    begin
    end;

    var
        Cust: Record Customer;
        Comms: Decimal;
        //CashPayType: Record "HR Leave Family Employees";
        companyInfo: Record "Company Information";
        NumberText: array[2] of Text[80];
        LastFieldNo: Integer;
        CheckReport: Report Check;
        LoanProduct: Code[20];
        LoansRec: Record "Loans Register";

    procedure CalAvailableBal()
    begin
    end;

    local procedure ConvertAmountToWords(Amount: Decimal): Text
    var
        Ones: array[20] of Text[20];
        Tens: array[10] of Text[20];
        NumHundreds: Integer;
        NumTens: Integer;
        NumOnes: Integer;
        Millions: Integer;
        Thousands: Integer;
        Hundreds: Integer;
        Result: Text;
    begin
        // Initialize word arrays
        Ones[1] := 'ONE';
        Ones[2] := 'TWO';
        Ones[3] := 'THREE';
        Ones[4] := 'FOUR';
        Ones[5] := 'FIVE';
        Ones[6] := 'SIX';
        Ones[7] := 'SEVEN';
        Ones[8] := 'EIGHT';
        Ones[9] := 'NINE';
        Ones[10] := 'TEN';
        Ones[11] := 'ELEVEN';
        Ones[12] := 'TWELVE';
        Ones[13] := 'THIRTEEN';
        Ones[14] := 'FOURTEEN';
        Ones[15] := 'FIFTEEN';
        Ones[16] := 'SIXTEEN';
        Ones[17] := 'SEVENTEEN';
        Ones[18] := 'EIGHTEEN';
        Ones[19] := 'NINETEEN';

        Tens[2] := 'TWENTY';
        Tens[3] := 'THIRTY';
        Tens[4] := 'FORTY';
        Tens[5] := 'FIFTY';
        Tens[6] := 'SIXTY';
        Tens[7] := 'SEVENTY';
        Tens[8] := 'EIGHTY';
        Tens[9] := 'NINETY';

        if Amount = 0 then
            exit('ZERO');

        Result := '';

        // Millions
        Millions := Amount div 1000000;
        if Millions > 0 then
            Result := ConvertGroupToWords(Millions, Ones, Tens) + ' MILLION';

        // Thousands
        Thousands := (Amount mod 1000000) div 1000;
        if Thousands > 0 then begin
            if Result <> '' then Result += ' ';
            Result += ConvertGroupToWords(Thousands, Ones, Tens) + ' THOUSAND';
        end;

        // Hundreds
        Hundreds := Amount mod 1000;
        if Hundreds > 0 then begin
            if Result <> '' then Result += ' ';
            Result += ConvertGroupToWords(Hundreds, Ones, Tens);
        end;

        exit(Result);
    end;

    local procedure ConvertGroupToWords(GroupValue: Integer; var Ones: array[20] of Text[20]; var Tens: array[10] of Text[20]): Text
    var
        NumHundreds: Integer;
        NumTens: Integer;
        NumOnes: Integer;
        Result: Text;
    begin
        NumHundreds := GroupValue div 100;
        NumTens := (GroupValue mod 100) div 10;
        NumOnes := GroupValue mod 10;

        Result := '';

        // Hundreds
        if NumHundreds > 0 then
            Result := Ones[NumHundreds] + ' HUNDRED';

        // Tens and Ones
        if NumTens >= 2 then begin
            if Result <> '' then Result += ' AND ';
            Result += Tens[NumTens];
            if NumOnes > 0 then
                Result += ' ' + Ones[NumOnes];
        end else if NumTens = 1 then begin
            if Result <> '' then Result += ' AND ';
            Result += Ones[10 + NumOnes];
        end else if NumOnes > 0 then begin
            if Result <> '' then Result += ' AND ';
            Result += Ones[NumOnes];
        end;

        exit(Result);
    end;

    // --> Reports ForNAV Autogenerated code - do not delete or modify
    var
        // [WithEvents]
        // ReportForNav : DotNet ForNavReport50387_v7_3_0_2559;
        ReportForNavOpenDesigner: Boolean;
        [InDataSet]
        ReportForNavAllowDesign: Boolean;

    // local procedure ReportsForNavInit();
    // var
    // 	ApplicationSystemConstants: Codeunit "Application System Constants";
    // 	addInFileName : Text;
    // 	tempAddInFileName : Text;
    // 	//path: DotNet System_IO_Path50387;
    // 	ReportForNavObject: Variant;
    // begin
    // 	// addInFileName := ApplicationPath() + 'Add-ins\ReportsForNAV_7_3_0_2559\ForNav.Reports.7.3.0.2559.dll';
    // 	// if not File.Exists(addInFileName) then begin
    // 	// 	tempAddInFileName := path.GetTempPath() + '\Microsoft Dynamics NAV\Add-Ins\' + ApplicationSystemConstants.PlatformFileVersion() + '\ForNav.Reports.7.3.0.2559.dll';
    // 	// 	if not File.Exists(tempAddInFileName) then
    // 	// 		Error('Please install the ForNAV DLL version 7.3.0.2559 in your service tier Add-ins folder under the file name "%1"\\If you already have the ForNAV DLL on the server, you should move it to this folder and rename it to match this file name.', addInFileName);
    // 	// end;
    // 	ReportForNavObject := ReportForNav.GetLatest(CurrReport.OBJECTID, CurrReport.Language, SerialNumber, UserId, CompanyName);
    // 	ReportForNav := ReportForNavObject;
    // 	ReportForNav.Init();
    // end;

    // local procedure ReportsForNavPre();
    // begin
    // 	ReportForNav.OpenDesigner:=ReportForNavOpenDesigner;
    // 	if not ReportForNav.Pre() then CurrReport.Quit();
    // end;

    // Reports ForNAV Autogenerated code - do not delete or modify -->
}
