#pragma warning disable AA0005, AA0008, AA0018, AA0021, AA0072, AA0137, AA0201, AA0204, AA0206, AA0218, AA0228, AL0254, AL0424, AS0011, AW0006 // ForNAV settings

Report 50413 "Holiday Fund1"
{
    RDLCLayout = './Layouts/Holiday Fund1.rdlc';
    DefaultLayout = RDLC;

    dataset
    {
        dataitem(Vendor; Vendor)
        {
            PrintOnlyIfDetail = false;
            RequestFilterFields = "No.", "Date Filter";
            column(ReportForNavId_4645; 4645) { } // Autogenerated by ForNav - Do not delete
            column(FORMAT_TODAY_0_4_; Format(Today, 0, 4))
            {
            }
            column(COMPANYNAME; COMPANYNAME)
            {
            }
            column(Company_Address; Company.Address)
            {
            }
            column(Company_Address2; Company."Address 2")
            {
            }
            column(Company_PhoneNo; Company."Phone No.")
            {
            }
            column(Company_Email; Company."E-Mail")
            {
            }
            column(Company_Picture; Company.Picture)
            {
            }
            column(CurrReport_PAGENO; CURRReport.PageNo)
            {
            }
            column(USERID; UserId)
            {
            }
            column(No; Vendor."No.")
            {
            }
            column(Name; Vendor.Name)
            {
            }
            column(Personal_No; Vendor."Personal No.")
            {
            }
            column(Employer_No; Vendor."Employer Code")
            {
            }
            column(ID_No; Vendor."ID No.")
            {
            }
            trigger OnAfterGetRecord();
            begin
                BaldateTXT := '01/01/10..' + Format(Baldate);

                CUST.Reset;
                CUST.SetRange(CUST."No.", "No.");
                CUST.SetFilter(CUST."Date Filter", BaldateTXT);
                if CUST.Find('-') then begin
                    CUST.CalcFields(CUST."Current Shares", CUST."Shares Retained", CUST."Insurance Fund");
                end;
                //DivBal:= "Dividend Amount" *-1;
                Balance6 := Balance6 + CUST."Dividend Amount";
                RNo := RNo + 1;
                Modify;
                /*
				Loan.RESET;
				Loan.SETRANGE(Loan."Client Code","No.");
				IF Loan.FIND('-') THEN BEGIN
					REPEAT
						Loan."Company Code":="Company Code";
						Loan.MODIFY;
					UNTIL Loan.NEXT=0;
				END;
				Loan.RESET;
				Loan.SETRANGE(Loan."BOSA No","No.");
				IF Loan.FIND('-') THEN BEGIN
					REPEAT
						Loan."Company Code":="Company Code";
						Loan.MODIFY;
					UNTIL Loan.NEXT=0;
				END;
				*/

            end;

        }
    }
    requestpage
    {
        SaveValues = false;
        layout
        {
            area(Content)
            {

            }
        }

    }

    trigger OnInitReport()
    begin
        Company.Get();
        Company.CalcFields(Company.Picture);
        ;

    end;

    trigger OnPostReport()
    begin
        ;
    end;

    trigger OnPreReport()
    begin
        /* IF "COMPY INFOR".GET THEN
         BEGIN
 "COMPY INFOR".CALCFIELDS("COMPY INFOR".Picture);
         NAME:="COMPY INFOR".Name;
         END;*/
        ;

    end;

    var
        RNo: Integer;
        BaldateTXT: Text[30];
        DivBal: Decimal;

        Balance6: Decimal;
        Company: Record "Company Information";
        Baldate: Date;

        CUST: Record Customer;



    // Reports ForNAV Autogenerated code - do not delete or modify -->
}
