#pragma warning disable AA0005, AA0008, AA0018, AA0021, AA0072, AA0137, AA0201, AA0204, AA0206, AA0218, AA0228, AL0254, AL0424, AS0011, AW0006 // ForNAV settings


Report 50950 "Loans Under Debt Coll. Report"
{
    RDLCLayout = './Layouts/Loans Under Debt Coll.Report.rdlc';
    DefaultLayout = RDLC;

    dataset
    {
        dataitem("Loans Register"; "Loans Register")
        {
            DataItemTableView = where("Loan Under Debt Collection" = filter(true));
            PrintOnlyIfDetail = false;
            RequestFilterFields = "Loan  No.", "Loan Product Type", "Client Code", "Loan Disbursement Date";
            column(ReportForNavId_4645; 4645) { } // Autogenerated by ForNav - Do not delete
            column(FORMAT_TODAY_0_4_; Format(Today, 0, 4))
            {
            }
            column(COMPANYNAME; COMPANYNAME)
            {
            }
            column(Company_Name; Company.Name)
            {
            }
            column(Company_Address; Company.Address)
            {
            }
            column(Company_Address_2; Company."Address 2")
            {
            }
            column(Company_Phone_No; Company."Phone No.")
            {
            }
            column(Company_Fax_No; Company."Fax No.")
            {
            }
            column(Company_Picture; Company.Picture)
            {
            }
            column(Company_Email; Company."E-Mail")
            {
            }
            column(CurrReport_PAGENO; CurrReport.PAGENO)
            {
            }
            column(USERID; UserId)
            {
            }
            column(VarCount; VarCount)
            {
            }
            column(VarAmountinArrears; VarAmountinArrears)
            {
            }
            column(RepaymentStartDate_LoansRegister; "Loans Register"."Repayment Start Date")
            {
            }
            column(OutstandingBalance_LoansRegister; "Loans Register"."Outstanding Balance")
            {
            }
            column(LoanNo_LoansRegister; "Loans Register"."Loan  No.")
            {
            }
            column(ApplicationDate_LoansRegister; "Loans Register"."Application Date")
            {
            }
            column(LoanProductType_LoansRegister; "Loans Register"."Loan Product Type")
            {
            }
            column(ClientCode_LoansRegister; "Loans Register"."Client Code")
            {
            }
            column(RequestedAmount_LoansRegister; "Loans Register"."Requested Amount")
            {
            }
            column(ApprovedAmount_LoansRegister; "Loans Register"."Approved Amount")
            {
            }
            column(ClientName_LoansRegister; "Loans Register"."Client Name")
            {
            }
            column(IssuedDate_LoansRegister; Format("Loans Register"."Issued Date"))
            {
            }
            column(Installments_LoansRegister; "Loans Register".Installments)
            {
            }
            column(LoanDisbursementDate_LoansRegister; "Loans Register"."Loan Disbursement Date")
            {
            }
            column(LoanUnderDebtCollection_LoansRegister; "Loans Register"."Loan Under Debt Collection")
            {
            }
            column(LoanDebtCollector_LoansRegister; "Loans Register"."Loan Debt Collector")
            {
            }
            column(LoanDebtCollectorInterest_LoansRegister; "Loans Register"."Loan Debt Collector Interest %")
            {
            }
            column(DebtCollectiondateAssigned_LoansRegister; Format("Loans Register"."Debt Collection date Assigned"))
            {
            }
            column(DebtCollectorName_LoansRegister; "Loans Register"."Debt Collector Name")
            {
            }
            column(DaysInArrears_LoansRegister; "Loans Register"."Days In Arrears")
            {
            }
            column(AmountinArrears_LoansRegister; "Loans Register"."Amount in Arrears")
            {
            }
            column(LoanProductTypeName_LoansRegister; "Loans Register"."Loan Product Type Name")
            {
            }
            column(LoanBalAsAtDebtCollection_LoansRegister; "Loans Register"."Loan Bal As At Debt Collection")
            {
            }
            trigger OnAfterGetRecord();
            begin
                VarAmountinArrears := 0;
                VarCount := VarCount + 1;
                /*//Get Arrears
				ObjRepaymentSchedule.RESET;
				ObjRepaymentSchedule.SETRANGE(ObjRepaymentSchedule."Loan No.","Loan  No.");
				IF ObjRepaymentSchedule.FINDSET=TRUE THEN
				  BEGIN
					IF ("Outstanding Balance">0) AND (Repayment<>0) THEN
					  BEGIN
						VarAmountinArrears:=SFactory.FnGetLoanAmountinArrears("Loan  No.");
						END;
					END;*/
                SFactory.FnGetLoanArrearsAmountII("Loans Register"."Loan  No.");
                "Loans Register".Modify;

            end;

        }
    }
    requestpage
    {
        SaveValues = false;
        layout
        {
            area(Content)
            {
                group(Options)
                {
                    Caption = 'Options';

                }
            }
        }

    }

    trigger OnInitReport()
    begin
        Company.Get();
        Company.CalcFields(Company.Picture);
        ;

    end;

    trigger OnPostReport()
    begin
    end;

    trigger OnPreReport()
    begin
    end;

    var
        Company: Record "Company Information";
        SFactory: Codeunit "Micropoint Factory";
        VarAmountinArrears: Decimal;
        ObjRepaymentSchedule: Record "Loan Repayment Schedule";
        VarCount: Integer;

    // --> Reports ForNAV Autogenerated code - do not delete or modify


    // Reports ForNAV Autogenerated code - do not delete or modify -->
}
