#pragma warning disable AA0005, AA0008, AA0018, AA0021, AA0072, AA0137, AA0201, AA0204, AA0206, AA0218, AA0228, AL0254, AL0424, AS0011, AW0006 // ForNAV settings


Report 50964 "Loans Recovery Logs"
{
    RDLCLayout = './Layouts/Loans Recovery Logs.rdlc';
    DefaultLayout = RDLC;

    dataset
    {
        dataitem("Loan Recovery Logs"; "Loan Recovery Logs")
        {
            PrintOnlyIfDetail = false;
            RequestFilterFields = "Member No", "Loan No", "Loan Product Type", "Log Date", "User ID";
            column(ReportForNavId_4645; 4645) { } // Autogenerated by ForNav - Do not delete
            column(FORMAT_TODAY_0_4_; Format(Today, 0, 4))
            {
            }
            column(COMPANYNAME; COMPANYNAME)
            {
            }
            column(Company_Name; Company.Name)
            {
            }
            column(Company_Address; Company.Address)
            {
            }
            column(Company_Address_2; Company."Address 2")
            {
            }
            column(Company_Phone_No; Company."Phone No.")
            {
            }
            column(Company_Fax_No; Company."Fax No.")
            {
            }
            column(Company_Picture; Company.Picture)
            {
            }
            column(Company_Email; Company."E-Mail")
            {
            }
            column(CurrReport_PAGENO; CurrReport.PAGENO)
            {
            }
            column(USERID; UserId)
            {
            }
            column(VarCount; VarCount)
            {
            }
            column(EntryNo_LoanRecoveryLogs; "Loan Recovery Logs"."Entry No")
            {
            }
            column(MemberNo_LoanRecoveryLogs; "Loan Recovery Logs"."Member No")
            {
            }
            column(MemberName_LoanRecoveryLogs; "Loan Recovery Logs"."Member Name")
            {
            }
            column(LoanNo_LoanRecoveryLogs; "Loan Recovery Logs"."Loan No")
            {
            }
            column(LoanProductType_LoanRecoveryLogs; "Loan Recovery Logs"."Loan Product Type")
            {
            }
            column(LoanBalance_LoanRecoveryLogs; "Loan Recovery Logs"."Loan Balance")
            {
            }
            column(LogDate_LoanRecoveryLogs; Format("Loan Recovery Logs"."Log Date", 0, '<Day,2> <Month Text,3> <Year4>'))
            {
            }
            column(UserID_LoanRecoveryLogs; "Loan Recovery Logs"."User ID")
            {
            }
            column(LogDescription_LoanRecoveryLogs; "Loan Recovery Logs"."Log Description")
            {
            }
            column(LoanProductName_LoanRecoveryLogs; "Loan Recovery Logs"."Loan Product Name")
            {
            }
            column(LoanAmountInArrears_LoanRecoveryLogs; "Loan Recovery Logs"."Loan Amount In Arrears")
            {
            }
            column(LoanArrearsDays_LoanRecoveryLogs; "Loan Recovery Logs"."Loan Arrears Days")
            {
            }
            trigger OnAfterGetRecord();
            begin
                VarAmountinArrears := 0;
                VarCount := VarCount + 1;
                //SFactory.FnGetLoanArrearsAmountII("Loans Register"."Loan  No.");
            end;

        }
    }
    requestpage
    {
        SaveValues = false;
        layout
        {
            area(Content)
            {
                group(Options)
                {
                    Caption = 'Options';

                }
            }
        }

    }

    trigger OnInitReport()
    begin
        Company.Get();
        Company.CalcFields(Company.Picture);


    end;

    trigger OnPostReport()
    begin

    end;

    trigger OnPreReport()
    begin

    end;

    var
        Company: Record "Company Information";
        SFactory: Codeunit "Micropoint Factory";
        VarAmountinArrears: Decimal;
        ObjRepaymentSchedule: Record "Loan Repayment Schedule";
        VarCount: Integer;

    // --> Reports ForNAV Autogenerated code - do not delete or modify

    // Reports ForNAV Autogenerated code - do not delete or modify -->
}
