#pragma warning disable AA0005, AA0008, AA0018, AA0021, AA0072, AA0137, AA0201, AA0204, AA0206, AA0218, AA0228, AL0254, AL0424, AS0011, AW0006 // ForNAV settings


Report 50400 "Loans Portfolio Aging - SASRA"
{
    RDLCLayout = './Layouts/Loans Portfolio Aging - SASRA.rdlc';
    DefaultLayout = RDLC;

    dataset
    {
        dataitem("Loan Portfolio Provision"; "Loan Portfolio Provision")
        {
            DataItemTableView = sorting("Loan No", "Report Date");
            RequestFilterFields = "Loan No", "Member No", Classification, Rescheduled, "Report Date";
            column(ReportForNavId_4645; 4645) { } // Autogenerated by ForNav - Do not delete
            column(FORMAT_TODAY_0_4_; Format(Today, 0, 4))
            {
            }
            column(COMPANYNAME; COMPANYNAME)
            {
            }
            column(Company_Name; Company.Name)
            {
            }
            column(Company_Address; Company.Address)
            {
            }
            column(Company_Address_2; Company."Address 2")
            {
            }
            column(Company_Phone_No; Company."Phone No.")
            {
            }
            column(Company_Fax_No; Company."Fax No.")
            {
            }
            column(Company_Picture; Company.Picture)
            {
            }
            column(Company_Email; Company."E-Mail")
            {
            }
            column(CurrReport_PAGENO; CurrReport.PageNo())
            {
            }
            column(USERID; UserId)
            {
            }
            column(LoanNo_LoanPortfolioProvision; "Loan Portfolio Provision"."Loan No")
            {
            }
            column(MemberNo_LoanPortfolioProvision; "Loan Portfolio Provision"."Member No")
            {
            }
            column(MemberName_LoanPortfolioProvision; "Loan Portfolio Provision"."Member Name")
            {
            }
            column(Performing_LoanPortfolioProvision; "Loan Portfolio Provision".Performing)
            {
            }
            column(Watch_LoanPortfolioProvision; "Loan Portfolio Provision".Watch)
            {
            }
            column(Substandard_LoanPortfolioProvision; "Loan Portfolio Provision".Substandard)
            {
            }
            column(Doubtful_LoanPortfolioProvision; "Loan Portfolio Provision".Doubtful)
            {
            }
            column(Loss_LoanPortfolioProvision; "Loan Portfolio Provision".Loss)
            {
            }
            column(OutstandingBalance_LoanPortfolioProvision; "Loan Portfolio Provision"."Outstanding Balance")
            {
            }
            column(ArrearsAmount_LoanPortfolioProvision; "Loan Portfolio Provision"."Arrears Amount")
            {
            }
            column(ArrearsDays_LoanPortfolioProvision; "Loan Portfolio Provision"."Arrears Days")
            {
            }
            column(Classification_LoanPortfolioProvision; "Loan Portfolio Provision".Classification)
            {
            }
            column(Rescheduled_LoanPortfolioProvision; "Loan Portfolio Provision".Rescheduled)
            {
            }
            column(ReportDate_LoanPortfolioProvision; "Loan Portfolio Provision"."Report Date")
            {
            }
            trigger OnPreDataItem();
            begin
                Company.Get();
                Company.CalcFields(Company.Picture);
                SFactory.FnUpdateLoanPortfolio(AsAt);
                "Loan Portfolio Provision".SetFilter("Loan Portfolio Provision"."Report Date", '%1', AsAt);
            end;

        }
    }
    requestpage
    {
        SaveValues = false;
        layout
        {
            area(Content)
            {
                field("As At"; AsAt)
                {
                    ApplicationArea = Basic;
                }

            }
        }

    }

    trigger OnInitReport()
    begin
        ;

    end;

    trigger OnPostReport()
    begin
        ;
    end;

    trigger OnPreReport()
    begin
        ;
    end;

    var
        Loans_Aging_Analysis__SASRA_CaptionLbl: label 'Loans Aging Analysis (SASRA)';
        CurrReport_PAGENOCaptionLbl: label 'Page';
        Loan_TypeCaptionLbl: label 'Loan Type';
        Staff_No_CaptionLbl: label 'Staff No.';
        Oustanding_BalanceCaptionLbl: label 'Oustanding Balance';
        PerformingCaptionLbl: label 'Performing';
        V1___30_Days_CaptionLbl: label '(1 - 30 Days)';
        V0_Days_CaptionLbl: label '(0 Days)';
        WatchCaptionLbl: label 'Watch';
        V31___180_Days_CaptionLbl: label '(31 - 180 Days)';
        SubstandardCaptionLbl: label 'Substandard';
        V181___360_Days_CaptionLbl: label '(181 - 360 Days)';
        DoubtfulCaptionLbl: label 'Doubtful';
        Over_360_DaysCaptionLbl: label 'Over 360 Days';
        LossCaptionLbl: label 'Loss';
        TotalsCaptionLbl: label 'Totals';
        CountCaptionLbl: label 'Count';
        Grand_TotalCaptionLbl: label 'Grand Total';
        AsAt: Date;
        Company: Record "Company Information";
        SFactory: Codeunit "Micropoint Factory";



    // Reports ForNAV Autogenerated code - do not delete or modify -->
}
