#pragma warning disable AA0005, AA0008, AA0018, AA0021, AA0072, AA0137, AA0201, AA0204, AA0206, AA0218, AA0228, AL0254, AL0424, AS0011, AW0006 // ForNAV settings

Report 50414 "Member List"
{
    RDLCLayout = './Layouts/Member List.rdlc';
    DefaultLayout = RDLC;

    dataset
    {
        dataitem("Members Register"; Customer)
        {
            DataItemTableView = sorting("No.") where("Customer Type" = filter(Member));
            RequestFilterFields = "No.", "Date Filter";
            column(ReportForNavId_4645; 4645) { } // Autogenerated by ForNav - Do not delete
            column(FORMAT_TODAY_0_4_; Format(Today, 0, 4))
            {
            }
            column(COMPANYNAME; COMPANYNAME)
            {
            }
            column(Company_Address; Company.Address)
            {
            }
            column(Company_Address2; Company."Address 2")
            {
            }
            column(Company_PhoneNo; Company."Phone No.")
            {
            }
            column(Company_Email; Company."E-Mail")
            {
            }
            column(Company_Picture; Company.Picture)
            {
            }
            column(CurrReport_PAGENO; currReport.PageNo)
            {
            }
            column(USERID; UserId)
            {
            }
            column(No; "Members Register"."No.")
            {
            }
            column(Name; "Members Register".Name)
            {
            }
            column(Personal_No; "Members Register"."Personal No")
            {
            }
            column(Status; "Members Register".Status)
            {
            }
            column(Registration_Date; "Members Register"."Registration Date")
            {
            }
            column(Entrance_Fee; "Members Register"."Registration Fee")
            {
            }
            column(Share_Capital; "Members Register"."Shares Retained")
            {
            }
            column(Deposits; "Members Register"."Monthly Contribution")
            {
                AutoCalcField = true;
            }
            column(Welfare; "Members Register"."Welfare Contribution")
            {
            }
            column(Dividend_Amount; "Members Register"."Dividend Amount")
            {
            }
            trigger OnAfterGetRecord();
            begin

            end;

        }
    }
    requestpage
    {
        SaveValues = false;
        layout
        {
            area(Content)
            {

            }
        }

    }

    trigger OnInitReport()
    begin
        Company.Get();
        Company.CalcFields(Company.Picture);
        ;

    end;

    trigger OnPostReport()
    begin
        ;
    end;

    trigger OnPreReport()
    begin
        /* IF "COMPY INFOR".GET THEN
         BEGIN
 "COMPY INFOR".CALCFIELDS("COMPY INFOR".Picture);
         NAME:="COMPY INFOR".Name;
         END;*/
        ;

    end;

    var
        RNo: Integer;
        BaldateTXT: Text[30];
        DivBal: Decimal;
        Loan: Record "Loans Register";
        Balance6: Decimal;
        Company: Record "Company Information";
        Baldate: Date;


    // Reports ForNAV Autogenerated code - do not delete or modify -->
}
